// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/favicon.ico": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/favicon.ico";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/favicon.ico.ts": {
    id: "routes/favicon.ico";
    page: "/favicon.ico";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/login": typeof import("./src/routes/login.tsx");
  "routes/favicon.ico": typeof import("./src/routes/favicon.ico.ts");
  "routes/dashboard": typeof import("./src/routes/dashboard.tsx");
};